### ISSUE TITLE
Headers already sent error after creating an account

### ISSUE THREAD

**Issue by evs-xsarus** [flowmailer/m2connector#7] opened 2020-06-10 07:02 UTC
When I create a new account, the account is created, but the redirected page (/customer/account/createpost/) shows:

```
#0 (Exception): Warning: Cannot modify header information - headers already sent by (output started at /var/www/tex/vendor/flowmailer/m2connector/Helper/API/FlowmailerAPI.php:108) in /var/www/tex/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 148
#1 setcookie() called at [vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:148]
#2 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie() called at [vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:121]
#3 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:138]
#4 Magento\Theme\Controller\Result\MessagePlugin->setCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:95]
#5 Magento\Theme\Controller\Result\MessagePlugin->afterRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#6 Magento\Framework\Controller\Result\Redirect\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Framework\Controller\Result\Redirect\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Controller/Result/Redirect/Interceptor.php:117]
#8 Magento\Framework\Controller\Result\Redirect\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#9 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#10 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
```
I'm running:

Magento 2.3.4
flowmailer/m2connector: 1.0.10

**Comment by flowmailer-richard** [comment] 2020-07-30 07:20
This was caused by error output where logging should be used, fixed by the commit above.

**Closed as completed by flowmailer-richard** 2020-07-30 07:20 UTC
